# Site settings
title: Intro to Probability and Statistics
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A first course in probability, statistical reasoning, and applied data analysis
  at Reed College.
baseurl: "/math-141"
url: "http://andrewpbray.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll
url2: "http://ismayc.github.io"
urllabel: "Andrew's Webpage"
url2label: "Chester's Webpage"

# Build settings
markdown: kramdown
