# Site settings
title: Intro to Probability and Statistics
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A first course in probability, statistical reasoning, and applied data analysis
  at Reed College taught by [Andrew Bray](andrewpbray.github.io) and [Chester Ismay](https://www.reed.edu/cis/about/staff/ismay.html).
baseurl: "/math-141"
url: "http://andrewpbray.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
