---
title: "Roadless USA"
output:
  html_document:
    theme: cerulean
    highlight: pygments
---

You will work in pairs, and will need one computer per group.  Please run the following lines in the Console of RStudio:

```{r load, message=FALSE, warning=FALSE}
require(mosaic)
getLocation <- function(counter) {
  googleMap(myroadless[counter, "latitude"], 
    myroadless[counter, "longitude"], 
    mark = TRUE, 
    maptype = "terrain", 
    radius = 1, 
    browse = TRUE)
}
nsamp <- 20
samples <- rgeo(n = nsamp, latlim = c(25, 50), lonlim = c(-65, -125))
myroadless <- data.frame(sample = 1:nsamp, 
  latitude = round(samples$lat, 4),
  longitude = round(samples$lon, 4),
  withinContinent = c(rep(NA, nsamp)),
  within1mile = c(rep(NA, nsamp)),
  location = character(nsamp))
myroadless
```

Now, one at a time, run the `getLocation()` commands in the Console of RStudio (one for each of the 20 locations you randomly sampled), taking notes of whether it was within the continental US, if so, whether it was within a mile of a road, as well as any notes about the location (please specify which state, ocean, or country it is in).  These should be entered into the table provided with this handout.  (The first time you should run `getLocation(1)`, then `getLocation(2)}`, etc.  If the Google map doesn't display, please ensure that your pop-up blocker is turned off.

1. Calculate $X$, the number within both the continental US and 1 mile of a road.

*Answers will vary here since pseudo-random numbers generate results.*

2. Calculate $n$, the total number within the continent.

*Answers will vary here since pseudo-random numbers generate results.*

3. Calculate $\hat{p} = X/n$, their ratio as your observed proportion.

*Answers will vary here since pseudo-random numbers generate results.*

4. Calculate a 95% confidence interval for the population proportion using the exact binomial method ` binom.test(X, n)`. Add this interval on the board (along with your values of $X$ and $n$).

*You should run `binom.test` here with something like `binom.test(X, n)` for your values of `X` and `n`.  You also should have extracted the confidence interval correctly from the output.*


## On your own

- Why did we use `binom.test(X, n)` instead of a adding and subtracting 1.96 SEs?

*The normal approximation is not valid here since the number of successes is below 10.*

- A student reports that their confidence interval for the proportion of the US that is within a mile of a road ranges from 0.38 to 0.84. They state that they are 95% confident that if they took another sample, the sample proportion would be in this interval. What is wrong with their reasoning?

*Confidence intervals are not predictors of sample statistics, but rather a range of plausible values for a parameter of interest.  If we took another sample and generated another confidence interval, we would be 95% confident that the true proportion of successes was in that interval.  This is true since if we continue to repeat the sampling process and building of confidence interval procedure, about 95% of the intervals will contain the true parameter value.*

- A student reports that their 95% confidence interval for the proportion of the US that is within a mile of a road ranges from 0.38 to 0.86. They state that it’s unlikely that the true proportion is equal to 0.9. Is their reasoning correct?

*Yes, since the confidence interval provides a range of plausible values for the true proportion, it is unlikely that 0.9 is a plausible value since it falls outside the range given.*

- One group finds that out of the 17 points they sampled, 11 of them were within a mile of a road. A student from a different group reports that she also found 11 points within a mile of a road, but sampled 19 points. She concludes that her standard error must be greater. Is this student correct?

*Standard error depends on both the sample proportion of successes and the sample size.  Let $\hat{p}_1$ correspond to the first group mentioned and $\hat{p}_2$ correspond to the second group mentioned.  Then, $\hat{p}_1 = 11/17 \approx `r phat1 <- round(11/17, digits = 2); phat1`$ and $\hat{p}_2 = 11/19 \approx `r phat2 <- round(11/19, digits = 2); phat2`$.  Thus,*

$$\text{SE}_1 = \sqrt{\dfrac{\hat{p}_1(1 - \hat{p}_1)}{n_1}} = \sqrt{\dfrac{`r (phat1)*(1-phat1)`}{17}} = `r SE1 <- sqrt(phat1 * (1 - phat1)/17); SE1`$$

*and*

$$\text{SE}_2 = \sqrt{\dfrac{\hat{p}_2(1 - \hat{p}_2)}{n_2}} = \sqrt{\dfrac{`r (phat2)*(1-phat2)`}{19}} = `r SE2 <- sqrt(phat2 * (1 - phat2)/19); SE2`.$$

*Thus, `r ifelse(SE2 > SE1, "the student is correct (her standard error is larger).", "the student is not correct (her standard error is not larger).")`*

<div id="license">
This is a product of OpenIntro that is released under a 
[Creative Commons Attribution-ShareAlike 3.0 Unported](http://creativecommons.org/licenses/by-sa/3.0). 
This lab was adapted for OpenIntro by Chester Ismay and Andrew Bray from an activity written by Nicholas Horton of Amherst College.
</div>
